### ISSUE TITLE
trying to figure out if i can make this system run from a item and you type in the ui instead of a command but need help

### ISSUE THREAD

**Issue by Lavishhugo** [tugamars/pv-pager#2]
trying to figure out if i can make this system run from a item and you type in the ui instead of a command but need help

**Comment by tugamars** [comment]
Yes, you can. 

However, you would need the UI to be in 2 steps: Channel and then Message.
You can easily do this with a textarea in place of the actual text and apply the same CSS. 

In terms of "realistic", you wouldn't page someone from a pager but from a phone i believe, so probably need to make another UI.
Look at the logic in the "page" function (server side), it should have all you need.

**Comment by Lavishhugo** [comment]
ok never really had experience with UI so could i get some help with the whole text arena and i understand that but i wanted it to be along the lines of every one has a pager number like through a license identifier like how u use discord roles as way for it to be broadcast or be able to send to the channel so i could give out individual numbers if u could help me edit it thst wopuld be fire also cuz this script can definetly be enhanced if i can figure this out
